# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ry4huCsVEp9EmWK0QUXvkOnEy4xaV5vY
"""

def add(n1,n2):
   return n1+n2
def sup(n1,n2):
   return n1-n2
def mul(n1,n2):
   return n1*n2
def div (n1,n2):
   if n2 >0:
     return n1/n2
   else:
       return-1
num1=int(input('enter first number :'))
num2=int(input('enter second number :'))
operation = input()
if operation =="+": 
    print("the sum is",add(num1,num2))
elif operation =="-": 
    print("the sup is",sup(num1,num2))
elif operation =="*":
    print("the mul is",mul(num1,num2))
elif operation =="/":
    print("the div is",div(num1,num2))
else:
     print("sad")